language: python

python:
  - "3.6"

cache:
  pip: true
  directories:
    - $HOME/.cache/pypoetry

before_install:
  - sudo apt-get update -q
  - sudo apt-get install libsodium-dev -y
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env

install:
  - poetry install -v

script:
  - poetry run pytest tests/
  - poetry run pytest examples/

before_deploy:
  - poetry build
  - export VERSION=$(cat pyproject.toml | awk '$1 ~ /^version/ {print $3}' | sed 's/"//g')
  - export TAG=${VERSION%.*}
  - git tag $TAG -f
  - git push origin $TAG -f

deploy:
  provider: pypi
  user: "__token__"
  password: $PYPI_TOKEN
  on:
    branch: master
    tags: false