language: python

python:
  - "3.6"

cache:
  pip: true
  directories:
    - $HOME/.cache/pypoetry

before_install:
  - sudo add-apt-repository ppa:chris-lea/libsodium
  - sudo apt-get update && sudo apt-get install -y libsodium-dev
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env

install:
  - poetry install -v

script:
  - poetry run pytest